###
# Configuration for Vagrant
###
name: wordpress
production:
  # This is used to automatically fetch data from a staging/production environment
  domain: foxland.seravo.fi
  ssh_port: 10598
  url: https://foxland.seravo.fi
development:
  # Domains are automatically mapped to Vagrant with /etc/hosts modifications
  domains:
    - foxland.test
  # If you want to use zeroconf (.local domains) in your network you can use this.
  #avahi: true
  # If you want to automatically pull stuff from production use 'always' or set
  # to 'never' to just silience the 'yes/no' question during 'vagrant up'.
  #pull_production_db: always
  #pull_production_plugins: always
  #pull_production_themes: always
